module.exports = new Set([
  'ada', 'adalah', 'adanya', 'adapun', 'agar', 'akan', 'akhirat', 'akibat',
  'akhirnya', 'akibatnya', 'aku', 'akulah', 'amat', 'amatlah', 'anda',
  'andalah', 'antar', 'antara', 'antaranya', 'apa', 'apabila', 'apakah',
  'apalagi', 'apapun', 'arah', 'artinya', 'asal', 'atas', 'atau', 'ataukah',
  'ataupun', 'awal', 'awalnya', 'bagai', 'bagaikan', 'bagaimana', 'bagaimanakah',
  'bagaimanapun', 'bagi', 'bagian', 'bahkan', 'bahwa', 'bahwasanya', 'banyak',
  'banyaknya', 'beberapa', 'begini', 'beginilah', 'begitu', 'begitulah',
  'begitupun', 'belum', 'belaka', 'beliau', 'berada', 'berakhir', 'berakhirilah',
  'berakhirnya', 'berarti', 'berawal', 'berbagai', 'berdiri', 'berekor',
  'berikut', 'berikutnya', 'berkali', 'berkali-kali', 'berkata', 'berkehendak',
  'berkeinginan', 'berkenaan', 'berlainan', 'berlalu', 'berlangsung', 'beli',
  'bernama', 'beroleh', 'bersama', 'bersamamu', 'bersamanya', 'bersiap',
  'bertanya', 'berturut', 'bertutur', 'berujar', 'berupa', 'besar', 'beserta',
  'betapa', 'bila', 'bilakah', 'boleh', 'bolehkah', 'bolehlah', 'buat',
  'bukan', 'bukankah', 'bukanlah', 'bukannya', 'bumi', 'cara', 'caranya',
  'cukup', 'cukupkah', 'cukuplah', 'cuma', 'dahulu', 'dalam', 'dan', 'dapat',
  'dari', 'daripada', 'dekat', 'demi', 'demikian', 'demikianlah', 'dengan',
  'depan', 'di', 'dia', 'diadakannya', 'diantara', 'diatas', 'dibalik',
  'didalam', 'diluar', 'dimana', 'dini', 'diri', 'dirinya', 'disini',
  'ditempuh', 'dua', 'dulu', 'empat', 'enggak', 'enggaknya', 'entah',
  'entahlah', 'hal', 'hampir', 'hanya', 'hanyalah', 'hari', 'harus',
  'haruslah', 'harusnya', 'hasil', 'hendak', 'hendaklah', 'hendaknya',
  'hingga', 'ia', 'ialah', 'ibarat', 'ikut', 'ingin', 'inginkah', 'inginkan',
  'ini', 'inilah', 'isi', 'istilah', 'itulah', 'jadi', 'jadilah', 'jadinya',
  'jangan', 'jangankan', 'janganlah', 'jauh', 'jelas', 'jenis', 'jika',
  'jikalau', 'juga', 'justru', 'kala', 'kalau', 'kalaulah', 'kalaupun',
  'kali', 'kalian', 'kami', 'kamilah', 'kamu', 'kamulah', 'kan', 'kapan',
  'kapankah', 'kapanpun', 'karena', 'karenanya', 'ke', 'kecil', 'kedua',
  'keduanya', 'kemudian', 'kena', 'kenapa', 'kepada', 'kepadanya', 'kepala',
  'kini', 'kinilah', 'kiranya', 'kita', 'kitalah', 'kok', 'kurang',
  'lagi', 'lagian', 'lah', 'lain', 'lainnya', 'lalu', 'lama', 'lamanya',
  'lanjut', 'lanjutnya', 'lebih', 'lewat', 'lima', 'lisan', 'luar',
  'macam', 'maka', 'makanya', 'makin', 'malah', 'malahan', 'mampu',
  'mampukah', 'mana', 'manakala', 'manalagi', 'masih', 'masihkah',
  'masing', 'mata', 'mau', 'maupun', 'melainkan', 'melalui', 'memang',
  'memastikan', 'memberi', 'membuat', 'memiliki', 'memperoleh', 'men',
  'menaiki', 'mendapat', 'mendatangkan', 'mengapa', 'mengatakan',
  'mengenai', 'mengerjakan', 'mengetahui', ' menggunakan', 'menjadi',
  'menuju', 'menurut', 'merupakan', 'meski', 'meskipun', 'meyakini',
  'meyakinkan', 'minta', 'mirip', 'misal', 'misalkan', 'moga', 'mungkin',
  'mungkinkah', 'naik', 'namun', 'nanti', 'nantinya', 'nyaris', 'nyata',
  'oleh', 'olehnya', 'orang', 'pada', 'padahal', 'padanya', 'paling',
  'panjang', 'pantas', 'para', 'pasti', 'pastilah', 'penting', 'per',
  'percuma', 'pernah', 'persis', 'pertama', 'perihal', ' pihak', 'pukul',
  'pula', 'pun', 'merupakan', 'misalnya', 'saja', 'saling', 'sama',
  'sambil', 'sampai', 'samping', 'sana', 'sangat', 'sangatlah', 'satu',
  'satu-satunya', 'satunya', 'saya', 'sayalah', 'cuma', 'se', 'sebab',
  'sebagai', 'sebagaimana', 'sebagian', 'sebaik', 'sebaiknya', 'sebaliknya',
  'sebanyak', 'sebarang', 'sebelum', 'sebelumnya', 'sebesar', 'sebetulnya',
  'sebisanya', 'sebuah', 'sebut', 'sebutlah', 'sebutnya', 'secara',
  'secukupnya', 'sedang', 'sedangkan', 'sedangkan', 'sedemikian', 'sederhana',
  'sedikit', 'sedikitnya', 'segala', 'segenap', 'seharusnya', 'sehingga',
  'seiring', 'sejak', 'sejauh', 'sejenak', 'sejumlah', 'sekadar', 'sekadarnya',
  'sekali', 'sekali-kali', 'sekalian', 'sekaligus', 'sekalipun', 'sekarang',
  'sekecil', 'seketika', 'sekiranya', 'sekitar', 'sekitarnya', 'sela',
  'selagi', 'selain', 'selaku', 'selalu', 'selama', 'selamanya', 'selanjutnya',
  'selesai', 'selesaikan', 'seluruh', 'semacam', 'semakin', 'semasa',
  'semasih', 'semata', 'semaunya', 'sementara', 'sempat', 'semua', 'semuanya',
  'semula', 'sendiri', 'sendirian', 'sendirinya', 'seolah', 'seorang',
  'sepanjang', 'sepantasnya', 'sepantasnyalah', 'seperlunya', 'seperti',
  'sepertinya', 'sepihak', 'sering', 'seringnya', 'serta', 'serupa', 'sesuai',
  'sesuatu', 'sesuatunya', 'sesudah', 'sesudahnya', 'setelah', 'setempat',
  'setengah', 'seterusnya', 'setiap', 'setiba', 'setibanya', 'setidak',
  'setidaknya', 'setinggi', 'seusai', 'sewaktu', 'siapa', 'siapakah',
  'siapapun', 'silakan', 'sini', 'sinilah', 'soal', 'suatu', 'sudah',
  'sudahkah', 'sudahlah', 'supaya', 'tadi', 'tadinya', 'tahu', 'tahun',
  'tak', 'tampak', 'tampaknya', 'tanpa', 'tanya', 'tapi', 'tegas', 'tegasnya',
  'telah', 'tempat', 'tengah', 'tentang', 'tepat', 'tepatnya', 'terakhir',
  'terasa', 'terbanyak', 'terdahulu', 'terdapat', 'terdiri', 'terhadap',
  'terhadapnya', 'termasuk', 'ternyata', 'tersebut', 'tersebutlah',
  'tertentu', 'terus', 'terutama', 'tesebut', 'tetap', 'tetapi', 'tiada',
  'tiadakan', 'tidak', 'tidakkah', 'tidaklah', 'tiga', 'tinggal', 'tolong',
  'tujuk', 'tujuan', 'turun', 'tutur', 'tuturnya', 'ucap', 'ucapnya',
  'ujar', 'ujarnya', 'umpama', 'umpamanya', 'untuk', 'untuk apa', 'usah',
  'usai', 'waduh', 'wah', 'wakil', 'waktu', 'waktunya', 'walau', 'walaupun',
  'ya', 'yaitu', 'yakin', 'yakni', 'yang',
]);
